# Generated by Django 4.2.5 on 2023-11-07 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('register_day', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'noticeboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Index', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'notify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotifyRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
