# Generated by Django 4.2.5 on 2023-10-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('register_day', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'noticeboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Index', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'notify',
                'managed': False,
            },
        ),
    ]
