# Generated by Django 4.2.5 on 2023-10-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Index', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'notify',
                'managed': False,
            },
        ),
    ]
