# Generated by Django 4.2.5 on 2023-10-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('register_day', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'noticeboard',
                'managed': False,
            },
        ),
    ]
