# Generated by Django 4.2.5 on 2023-11-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotifyRead',
        ),
    ]
